[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/editor.html"
  [headers.values]
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Embedder-Policy = "require-corp"
    Cross-Origin-Resource-Policy = "same-origin"

[[headers]]
  for = "/js/*"
  [headers.values]
    Cross-Origin-Resource-Policy = "cross-origin"

[[headers]]
  for = "/css/*"
  [headers.values]
    Cross-Origin-Resource-Policy = "cross-origin"

[[redirects]]
  from = "/editor"
  to = "/editor.html"
  status = 200

[[redirects]]
  from = "/terms"
  to = "/pages/terms.html"
  status = 200

[[redirects]]
  from = "/privacy"
  to = "/pages/privacy.html"
  status = 200

[[redirects]]
  from = "/sitemap"
  to = "/pages/sitemap.html"
  status = 200
